name: Deploy win95react
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: /usr/bin/npm install
    - name: Build app
      run: /usr/bin/npm run build
    - name: Launch
      run: cp -r build/* /var/www/html/
